FROM registry.fedoraproject.org/f32/fedora-toolbox:32

ENV PLAYBOOKS ~/Projets/infra-lucca

RUN dnf upgrade -y \
 && dnf install -y \
      fish \
      fzf \
      genisoimage \
      jq \
      p7zip \
      ripgrep \
      syslinux-nonlinux \
      tmux \
      vim \
      xorriso \
 && dnf clean all

COPY install-playbooks.sh /usr/local/bin/install-playbooks.sh
